export const PACKAGE_NAME = "@openokr/method";

export {
  isTermKey,
  type ResolvedTerminology,
  resolveTerminology,
  TERM_KEYS,
  TERMINOLOGY,
  type TermDefinition,
  type TerminologyOverrides,
  type TerminologyProblem,
  type TerminologyValidation,
  type TermKey,
  type TermLabel,
  termLabelSchema,
  validateTerminology,
} from "./terminology.ts";
export {
  CHECK_IN_FREQUENCIES,
  type CheckInFrequency,
  COACH_STRICTNESS,
  type CoachStrictness,
  canonThresholds,
  ISO_WEEKDAYS,
  isThresholdKey,
  type ResolvedThresholds,
  resolveThresholds,
  THRESHOLD_KEYS,
  THRESHOLDS,
  type ThresholdGroup,
  type ThresholdKey,
  type ThresholdOverrides,
  type ThresholdParameter,
  type ThresholdProblem,
  type ThresholdValue,
  thresholdsInGroup,
  type ValidationResult,
  validateOverrides,
} from "./thresholds.ts";
