export const PACKAGE_NAME = "@openokr/method";

export {
  ALIGNMENT_LEVEL_ORDER,
  type AlignmentFinding,
  type AlignmentGoal,
  type AlignmentGraph,
  type AlignmentPenalties,
  type AlignmentResult,
  type AlignmentRuleKey,
  type AlignmentScope,
  type AlignmentSeverity,
  alignmentHealthy,
  alignmentScore,
} from "./alignment.ts";
export {
  type BlockerEscalation,
  type BlockerLadderHours,
  escalationFor,
  type RankableBlocker,
  type RankedBlocker,
  rankBlockers,
} from "./blocker-board.ts";
export {
  type BookedRitual,
  type CadenceCoverage,
  type CadencePlanOptions,
  type CadenceWindow,
  cadenceCoverage,
  planCycleCadence,
  type RitualWeekday,
} from "./cadence-booking.ts";
export {
  cycleClosingDue,
  cycleStartsDue,
  planningOpensDue,
  publicationCountdownMilestone,
  reviewPreparationDue,
  type SessionLifecycleStage,
  sessionLifecycleStage,
} from "./countdown.ts";
export {
  type DigestBlocker,
  type DigestRisk,
  type WeeklyDigestInput,
  weeklyDigestLines,
  weeklyDigestNumbers,
} from "./digest.ts";
export {
  averageConfidence,
  type Divergence,
  type DivergenceInput,
  type DivergenceKind,
  divergences,
} from "./divergence.ts";
export {
  applyEnforcement,
  CHECK_DEFAULT_LEVELS,
  type EnforcementLevel,
  enforcementLevel,
} from "./enforcement.ts";
export {
  acknowledgementEscalation,
  blockerEscalation,
  type Escalation,
  type EscalationRole,
  escalation,
} from "./escalation.ts";
export {
  guidanceForPhase,
  HORIZONS,
  type Horizon,
  PHASE_GUIDANCE,
  type PhaseGuidance,
  SUGGESTED_TIMELINE,
  type TimelineRow,
} from "./guidance.ts";
export {
  KPI_DIRECTIONS,
  KPI_FREQUENCIES,
  KPI_STATES,
  type KpiAchievement,
  type KpiCorridor,
  type KpiDiagnostic,
  type KpiDirection,
  type KpiFrequency,
  type KpiState,
  kpiAchievement,
  kpiState,
  type LocalDate,
  normalisePeriod,
  type RecoveryLink,
} from "./kpi.ts";
export {
  aggregateForPeriod,
  type CascadeResult as KpiCascadeResult,
  cascadeOrder,
  type DependencyEdge,
  KPI_AGGREGATES,
  type KpiAggregate,
  type SourceRecord,
} from "./kpi-aggregate.ts";
export {
  evaluateFormula,
  FORMULA_MAX_DEPTH,
  FORMULA_MAX_NODES,
  FORMULA_MAX_REFERENCES,
  type FormulaDiagnostic,
  type FormulaNode,
  type FormulaProblem,
  type FormulaResult,
  type FormulaShape,
  formulaNodeSchema,
  validateFormula,
} from "./kpi-formula.ts";
export {
  draftRecovery,
  type EffectiveHealth,
  type EffectiveHealthInput,
  kpiEffectiveHealth,
  RECOVERY_PLACEHOLDER_TITLE,
  type RecoveryCloseInput,
  type RecoveryDiagnostic,
  type RecoveryDraft,
  type RecoveryKeyResultDraft,
  type RecoveryTreeInput,
  type RecoveryTreeNode,
  type RecoveryTreeRoot,
  shouldProposeRecovery,
  shouldProposeRecoveryClose,
} from "./kpi-recovery.ts";
export {
  type LinkedWork,
  type LinkedWorkDivergence,
  type LinkedWorkDivergenceInput,
  linkedWorkDivergence,
  linkedWorkShare,
} from "./linked-work.ts";
export {
  type CycleFacts,
  decide,
  draftingWaitsForPhases,
  isEasing,
  type PolicyDecision,
  type PolicyIntent,
  planningWindow,
  policyNeedsPhases,
} from "./policy.ts";
export {
  CHECK_ENFORCEMENT,
  type CheckEnforcement,
  defaultOkrKind,
  defaultPractice,
  describe as describePracticeSetting,
  differencesFromProfile,
  GATE_ENFORCEMENT,
  GATE_NUMBERS,
  type GateEnforcement,
  type GateNumber,
  isPracticeKey,
  isProfileKey,
  KEY_RESULT_KINDS,
  type KeyResultKind,
  keyResultKindsInUse,
  levelsInUse,
  OKR_LEVELS,
  type OkrLevel,
  okrKindsInUse,
  PRACTICE,
  PRACTICE_CHECK_IDS,
  PRACTICE_KEYS,
  PROFILE_KEYS,
  PROFILES,
  type PracticeChange,
  type PracticeCheckId,
  type PracticeGroup,
  type PracticeKey,
  type PracticeOverrides,
  type PracticeProblem,
  type PracticeSetting,
  type PracticeValidation,
  type PracticeValue,
  type ProfileDefinition,
  type ProfileKey,
  type ProfileSwitch,
  practiceInGroup,
  type ResolvedPractice,
  resolvePractice,
  switchProfile,
  type ThresholdChange,
  validatePracticeOverrides,
} from "./practice.ts";
export {
  ALIGNMENT_CHECKS,
  type AlignmentCheckInput,
  type ConditionRow,
  CYCLE_CHECKS,
  type CycleCheckInput,
  END_STATE_SHAPES,
  evaluateAlignment,
  evaluateCycle,
  evaluateKeyResults,
  evaluateObjective,
  examplesFor,
  KEY_RESULT_CHECKS,
  type KeyResultInput,
  type KeyResultSetInput,
  type KeyResultVerdict,
  matchesEndStateShape,
  OBJECTIVE_CHECKS,
  type ObjectiveInput,
  QUALITY_EXAMPLES,
  QUALITY_WORD_LISTS,
  type QualityCheck,
  type QualityExample,
  type QualityStatus,
  type QualityVerdict,
  strengthScore,
} from "./quality.ts";
export {
  belowCommittedFloor,
  type CascadeGoal,
  type CascadeResult,
  COMMITTED_FLOOR_TEXT,
  type ComputedScoreInput,
  type ConfidenceBand,
  type ConfidenceVerdict,
  cascadeProgress,
  committedShareMet,
  computedScore,
  confidenceBand,
  cycleScore,
  type DraftVerdict,
  draftVerdict,
  type Forecast,
  type ForecastPoint,
  type GoalHealth,
  goalHealth,
  type HealthInput,
  type KeyResultDirection,
  type KeyResultProgressInput,
  type KindedScore,
  keyResultProgress,
  needsRootCause,
  type OkrKind,
  objectiveScore,
  type PortfolioVerdict,
  type ProgressSignal,
  portfolioVerdict,
  portfolioVerdictOf,
  progressSignal,
  round2,
  SCORE_NOTE_TEXT,
  type ScoreBand,
  type ScoredKeyResult,
  type ScoreNote,
  scoreBand,
  scoreNote,
  shareInsideBand,
  TOO_SAFE_TEXT,
  tooSafePattern,
  trendForecast,
  type ValuePoint,
  type WeightedItem,
  weightedProgress,
} from "./scoring.ts";
export {
  BLOCKER_TYPE_DEFINITIONS,
  CLOSE_DECISION_MEANINGS,
  type Diagnosis,
  type DiagnosisKind,
  lowestProcessHealthStatement,
  MANAGEMENT_RETRO_QUESTIONS,
  MID_CYCLE_CALIBRATION,
  PROCESS_HEALTH_STATEMENTS,
  REVIEW_STAGE_KEYS,
  REVIEW_STAGES,
  type ReviewAct,
  type ReviewStage,
  type ReviewStageKey,
  RHYTHM_STATEMENTS,
  RITUALS,
  type Ritual,
  type RitualKind,
  ROOT_CAUSES,
  type RoomPulseBand,
  type RoomPulseRead,
  reviewStageKey,
  reviewStages,
  rhythmDiagnostic,
  rhythmScore,
  roomPulseRead,
  type TimedReviewStage,
  WEEKLY_STAGE_KEYS,
  WEEKLY_STEPS,
  type WeeklyStageKey,
  type WeeklyStep,
} from "./sessions.ts";
export {
  afterWeeklyCheckIn,
  currentStreakOn,
  type StreakState,
  weekStartOf,
} from "./streak.ts";
export {
  deferralFor,
  insideQuietHours,
  type SuppressionInput,
  type SuppressionReason,
  suppressionFor,
} from "./suppression.ts";
export {
  isTermKey,
  type ResolvedTerminology,
  resolveTerminology,
  TERM_KEYS,
  TERMINOLOGY,
  type TermDefinition,
  type TerminologyOverrides,
  type TerminologyProblem,
  type TerminologyValidation,
  type TermKey,
  type TermLabel,
  termLabelSchema,
  validateTerminology,
} from "./terminology.ts";
export {
  CHECK_IN_FREQUENCIES,
  type CheckInFrequency,
  COACH_STRICTNESS,
  type CoachStrictness,
  canonThresholds,
  ISO_WEEKDAYS,
  isThresholdKey,
  type ResolvedThresholds,
  resolveThresholds,
  THRESHOLD_KEYS,
  THRESHOLDS,
  type ThresholdGroup,
  type ThresholdKey,
  type ThresholdOverrides,
  type ThresholdParameter,
  type ThresholdProblem,
  type ThresholdValue,
  thresholdsInGroup,
  type ValidationResult,
  validateOverrides,
} from "./thresholds.ts";
export {
  closeIsSandbagged,
  commitmentDueToday,
  committedBelowFloor,
  confidenceIsCritical,
  draftIsSandbagged,
  objectivesOverCap,
  phasesClosingToday,
  streakAtRisk,
} from "./trigger-conditions.ts";
export {
  deterministicTriggers,
  isTriggerKey,
  TRIGGER_CATALOGUE,
  type Trigger,
  type TriggerKey,
  type TriggerOwner,
  trigger,
} from "./triggers.ts";
export {
  type CycleWorkflowInput,
  canPublish,
  type FrameSnapshot,
  GATE_TITLES,
  type GateResult,
  type GoalSnapshot,
  INPUT_PACK_ITEMS,
  type InitiativeSnapshot,
  type KeyResultSnapshot,
  PHASE_TITLES,
  type PhaseResult,
  type PredicateState,
  type PublishScope,
  phaseCompletion,
  phaseWorkAllowed,
  publishGates,
  workingDaysBetween,
} from "./workflow.ts";
