export const PACKAGE_NAME = "@openokr/method";

export {
  ALIGNMENT_LEVEL_ORDER,
  type AlignmentFinding,
  type AlignmentGoal,
  type AlignmentGraph,
  type AlignmentPenalties,
  type AlignmentResult,
  type AlignmentRuleKey,
  type AlignmentScope,
  type AlignmentSeverity,
  alignmentHealthy,
  alignmentScore,
} from "./alignment.ts";
export {
  cycleClosingDue,
  cycleStartsDue,
  planningOpensDue,
  publicationCountdownMilestone,
  reviewPreparationDue,
  type SessionLifecycleStage,
  sessionLifecycleStage,
} from "./countdown.ts";
export {
  BLOCKER_CLOCK_HOURS,
  type DigestBlocker,
  type DigestRisk,
  type WeeklyDigestInput,
  weeklyDigestLines,
  weeklyDigestNumbers,
} from "./digest.ts";
export {
  averageConfidence,
  type Divergence,
  type DivergenceInput,
  type DivergenceKind,
  divergences,
} from "./divergence.ts";
export {
  acknowledgementEscalation,
  blockerEscalation,
  type Escalation,
  type EscalationRole,
  escalation,
} from "./escalation.ts";
export {
  guidanceForPhase,
  HORIZONS,
  type Horizon,
  PHASE_GUIDANCE,
  type PhaseGuidance,
  SUGGESTED_TIMELINE,
  type TimelineRow,
} from "./guidance.ts";
export {
  KPI_DIRECTIONS,
  KPI_FREQUENCIES,
  KPI_STATES,
  type KpiAchievement,
  type KpiCorridor,
  type KpiDiagnostic,
  type KpiDirection,
  type KpiFrequency,
  type KpiState,
  kpiAchievement,
  kpiState,
  type LocalDate,
  normalisePeriod,
  type RecoveryLink,
} from "./kpi.ts";
export {
  aggregateForPeriod,
  type CascadeResult as KpiCascadeResult,
  cascadeOrder,
  type DependencyEdge,
  KPI_AGGREGATES,
  type KpiAggregate,
  type SourceRecord,
} from "./kpi-aggregate.ts";
export {
  evaluateFormula,
  FORMULA_MAX_DEPTH,
  FORMULA_MAX_NODES,
  FORMULA_MAX_REFERENCES,
  type FormulaDiagnostic,
  type FormulaNode,
  type FormulaProblem,
  type FormulaResult,
  type FormulaShape,
  formulaNodeSchema,
  validateFormula,
} from "./kpi-formula.ts";
export {
  draftRecovery,
  type EffectiveHealth,
  type EffectiveHealthInput,
  kpiEffectiveHealth,
  RECOVERY_PLACEHOLDER_TITLE,
  type RecoveryCloseInput,
  type RecoveryDiagnostic,
  type RecoveryDraft,
  type RecoveryKeyResultDraft,
  type RecoveryTreeInput,
  type RecoveryTreeNode,
  type RecoveryTreeRoot,
  shouldProposeRecovery,
  shouldProposeRecoveryClose,
} from "./kpi-recovery.ts";
export {
  ALIGNMENT_CHECKS,
  type AlignmentCheckInput,
  applyStrictness,
  type ConditionRow,
  CYCLE_CHECKS,
  type CycleCheckInput,
  evaluateAlignment,
  evaluateCycle,
  evaluateKeyResults,
  evaluateObjective,
  examplesFor,
  KEY_RESULT_CHECKS,
  type KeyResultInput,
  type KeyResultSetInput,
  type KeyResultVerdict,
  OBJECTIVE_CHECKS,
  type ObjectiveInput,
  QUALITY_EXAMPLES,
  QUALITY_WORD_LISTS,
  type QualityCheck,
  type QualityExample,
  type QualityStatus,
  type QualityVerdict,
  strengthScore,
} from "./quality.ts";
export {
  type CascadeGoal,
  type CascadeResult,
  type ConfidenceBand,
  type ConfidenceVerdict,
  cascadeProgress,
  confidenceBand,
  cycleScore,
  type DraftVerdict,
  draftVerdict,
  type Forecast,
  type ForecastPoint,
  type GoalHealth,
  goalHealth,
  type HealthInput,
  type KeyResultDirection,
  type KeyResultProgressInput,
  keyResultProgress,
  objectiveScore,
  type PortfolioVerdict,
  type ProgressSignal,
  portfolioVerdict,
  portfolioVerdictOf,
  progressSignal,
  round2,
  type ScoreAnnotation,
  type ScoreBand,
  type ScoredKeyResult,
  scoreAnnotation,
  scoreBand,
  trendForecast,
  type WeightedItem,
  weightedProgress,
} from "./scoring.ts";
export {
  BLOCKER_TYPE_DEFINITIONS,
  CLOSE_DECISION_MEANINGS,
  type Diagnosis,
  type DiagnosisKind,
  lowestProcessHealthStatement,
  MANAGEMENT_RETRO_QUESTIONS,
  PROCESS_HEALTH_STATEMENTS,
  REVIEW_STAGE_KEYS,
  REVIEW_STAGES,
  type ReviewAct,
  type ReviewStage,
  type ReviewStageKey,
  RHYTHM_STATEMENTS,
  RITUALS,
  type Ritual,
  type RitualKind,
  ROOT_CAUSES,
  type RoomPulseBand,
  type RoomPulseRead,
  reviewStageKey,
  reviewStages,
  rhythmDiagnostic,
  rhythmScore,
  roomPulseRead,
  type TimedReviewStage,
  WEEKLY_STAGE_KEYS,
  WEEKLY_STEPS,
  type WeeklyStageKey,
  type WeeklyStep,
} from "./sessions.ts";
export {
  insideQuietHours,
  type SuppressionInput,
  type SuppressionReason,
  suppressionFor,
} from "./suppression.ts";
export {
  isTermKey,
  type ResolvedTerminology,
  resolveTerminology,
  TERM_KEYS,
  TERMINOLOGY,
  type TermDefinition,
  type TerminologyOverrides,
  type TerminologyProblem,
  type TerminologyValidation,
  type TermKey,
  type TermLabel,
  termLabelSchema,
  validateTerminology,
} from "./terminology.ts";
export {
  CHECK_IN_FREQUENCIES,
  type CheckInFrequency,
  COACH_STRICTNESS,
  type CoachStrictness,
  canonThresholds,
  ISO_WEEKDAYS,
  isThresholdKey,
  type ResolvedThresholds,
  resolveThresholds,
  THRESHOLD_KEYS,
  THRESHOLDS,
  type ThresholdGroup,
  type ThresholdKey,
  type ThresholdOverrides,
  type ThresholdParameter,
  type ThresholdProblem,
  type ThresholdValue,
  thresholdsInGroup,
  type ValidationResult,
  validateOverrides,
} from "./thresholds.ts";
export {
  deterministicTriggers,
  isTriggerKey,
  TRIGGER_CATALOGUE,
  type Trigger,
  type TriggerOwner,
  trigger,
} from "./triggers.ts";
export {
  type CycleWorkflowInput,
  canPublish,
  type FrameSnapshot,
  GATE_TITLES,
  type GateResult,
  type GoalSnapshot,
  INPUT_PACK_ITEMS,
  type KeyResultSnapshot,
  PHASE_TITLES,
  type PhaseResult,
  type PredicateState,
  phaseCompletion,
  phaseWorkAllowed,
  publishGates,
  workingDaysBetween,
} from "./workflow.ts";
