/**
 * Primary keys: time-ordered UUIDs generated by the application
 * (TECHNICAL-PLAN §3).
 *
 * Two reasons the plan asks for time-ordered rather than random keys. Index
 * locality: a random v4 key scatters inserts across the whole B-tree, so a
 * busy table keeps dirtying pages all over disk, while a v7 key appends.
 * Deterministic assignment: an importer needs the key before the row exists,
 * so it can wire up references in one pass.
 *
 * This is RFC 9562 version 7: 48 bits of Unix milliseconds, then the version
 * and variant bits, then random. Postgres 17 has no `uuidv7()` of its own, so
 * the generator lives here and the tables carry no database-side default. A
 * row arriving without an id is a bug worth failing on rather than papering
 * over with a random key.
 */
import { randomBytes } from "node:crypto";

/**
 * A new time-ordered UUID.
 *
 * Two ids generated inside the same millisecond order randomly against each
 * other. RFC 9562 allows that, and it costs nothing here: ordering matters at
 * the granularity of index pages, not individual rows.
 */
export function newId(): string {
  const bytes = randomBytes(16);
  const milliseconds = Date.now();

  // The first 48 bits are the timestamp, most significant byte first.
  bytes[0] = Math.floor(milliseconds / 2 ** 40) & 0xff;
  bytes[1] = Math.floor(milliseconds / 2 ** 32) & 0xff;
  bytes[2] = Math.floor(milliseconds / 2 ** 24) & 0xff;
  bytes[3] = Math.floor(milliseconds / 2 ** 16) & 0xff;
  bytes[4] = Math.floor(milliseconds / 2 ** 8) & 0xff;
  bytes[5] = milliseconds & 0xff;

  // Version 7 in the high nibble of byte 6, variant 10 in the top bits of
  // byte 8. Everything else stays random.
  bytes[6] = ((bytes[6] as number) & 0x0f) | 0x70;
  bytes[8] = ((bytes[8] as number) & 0x3f) | 0x80;

  const hex = bytes.toString("hex");
  return [
    hex.slice(0, 8),
    hex.slice(8, 12),
    hex.slice(12, 16),
    hex.slice(16, 20),
    hex.slice(20, 32),
  ].join("-");
}

/** The millisecond a v7 id was generated at. Used by tests and diagnostics. */
export function idTimestamp(id: string): number {
  return Number.parseInt(id.replace(/-/g, "").slice(0, 12), 16);
}
