export const PACKAGE_NAME = "@openokr/db";

export {
  type ColumnExpectation,
  type DataChangeBatchResult,
  type DataChangeClient,
  DataChangeError,
  type DataChangeOutcome,
  type DataChangeScript,
  type RunDataChangesOptions,
  runDataChanges,
} from "./data-change.ts";
export {
  APPEND_ONLY_TABLES,
  type GrantOptions,
  grantAppPrivileges,
} from "./grants.ts";
export { idTimestamp, newId } from "./id.ts";
export {
  type MigrationClient,
  MigrationError,
  type RunMigrationsOptions,
  runMigrations,
} from "./migrate.ts";
export {
  lintMigrationDirs,
  lintMigrationSql,
  type MigrationLintResult,
} from "./migration-lint.ts";
export {
  enqueueOutbox,
  type OutboxMessage,
  type OutboxPayload,
} from "./outbox.ts";
export {
  type EnsureRolesOptions,
  ensureRoles,
  type SqlRunner,
} from "./roles.ts";
export {
  type AccessBinding,
  type AccessContext,
  type AccessGroup,
  type AccessGroupKind,
  type AccessGroupMembership,
  type AccessRoleTag,
  accessBindings,
  accessContexts,
  accessGroupMemberships,
  accessGroups,
} from "./schema/access.ts";
export {
  AGENT_AUTONOMIES,
  AGENT_KINDS,
  AGENT_RUN_STATUSES,
  AGENT_SCHEDULES,
  type Agent,
  type AgentAutonomy,
  type AgentKind,
  type AgentRun,
  type AgentRunLogEntry,
  type AgentRunStatus,
  type AgentSchedule,
  type AgentTask,
  agentRuns,
  agents,
  PROPOSED_CHANGE_STATUSES,
  type ProposedChange,
  type ProposedChangeStatus,
  proposedChanges,
} from "./schema/agents.ts";
export {
  AI_PROVIDER_KINDS,
  type AICredential,
  type AICredentialStatus,
  type AIProviderConfig,
  type AIProviderKind,
  aiCredentials,
  aiProviders,
} from "./schema/ai.ts";
export {
  type AIFeatureSetting,
  type AIModel,
  type AIModelPolicy,
  type AIPrompt,
  aiFeatureSettings,
  aiModelPolicies,
  aiModels,
  aiPrompts,
  MODEL_TIERS,
  type ModelTier,
} from "./schema/ai-models.ts";
export {
  type AIBudget,
  type AIUsageEvent,
  aiBudgets,
  aiUsageEvents,
  BUDGET_METRICS,
  BUDGET_PERIODS,
  BUDGET_SCOPES,
  type BudgetMetric,
  type BudgetPeriod,
  type BudgetScope,
  USAGE_SOURCES,
  type UsageSource,
  type UsageStatus,
} from "./schema/ai-usage.ts";
export {
  ALIGNMENT_FINDING_KINDS,
  ALIGNMENT_FINDING_SCOPES,
  ALIGNMENT_FINDING_SOURCES,
  ALIGNMENT_FINDING_STATES,
  ALIGNMENT_SEVERITIES,
  type AlignmentFindingKind,
  type AlignmentFindingRow,
  type AlignmentFindingScope,
  type AlignmentFindingSource,
  type AlignmentFindingState,
  type AlignmentSeverity,
  alignmentFindings,
  type GoalDependencyRow,
  goalDependencies,
  type KeyResultDependencyRow,
  keyResultDependencies,
} from "./schema/alignment.ts";
export {
  type Activity,
  type ActorKind,
  type AuditEvent,
  activities,
  auditEvents,
} from "./schema/audit.ts";
export {
  accounts,
  authSchema,
  passkeys,
  sessions,
  twoFactors,
  users,
  verifications,
} from "./schema/auth.ts";
export { type Blob, type BlobStatus, blobs } from "./schema/blobs.ts";
export {
  CHECK_IN_STATES,
  CHECK_IN_STATUSES,
  type CheckIn,
  type CheckInSnapshot,
  type CheckInState,
  type CheckInStatus,
  type CheckInVote,
  checkInSnapshots,
  checkIns,
  checkInVotes,
  type SnapshotEntry,
} from "./schema/check-ins.ts";
export {
  COMMENT_SUBJECT_TYPES,
  type Comment,
  type CommentSubjectType,
  comments,
  type Reaction,
  reactions,
} from "./schema/comments.ts";
export {
  type CycleBaselineHealth,
  type CycleCalibration,
  type CycleCapacityNote,
  type CycleFocusKeyResult,
  type CycleGateStateRow,
  type CycleIssue,
  type CyclePackItem,
  type CyclePriority,
  type CyclePriorScore,
  type CycleRevalidation,
  cycleBaselineHealth,
  cycleCalibrations,
  cycleCapacityNotes,
  cycleFocusKeyResults,
  cycleGateState,
  cycleIssues,
  cyclePackItems,
  cyclePriorities,
  cyclePriorScores,
  cycleRevalidations,
  ISSUE_SOURCES,
  type IssueSource,
} from "./schema/cycle-workflow.ts";
export {
  type AnnualFrame,
  type AnnualStrategy,
  annualFrames,
  annualStrategies,
  CYCLE_CADENCES,
  CYCLE_MODES,
  CYCLE_STATUSES,
  type Cycle,
  type CycleCadence,
  type CycleMode,
  type CycleSessionDate,
  type CycleStatus,
  cycles,
  GOAL_LEVELS,
  type GoalLevel,
  type RhythmSettingsRow,
  rhythmSettings,
} from "./schema/cycles.ts";
export {
  EMBEDDABLE_ENTITY_TYPES,
  type EmbeddableEntityType,
  type Embedding,
  embeddings,
} from "./schema/embeddings.ts";
export {
  CAPACITY_VERDICTS,
  type CapacityVerdict,
  GOAL_CLOSE_DECISIONS,
  GOAL_HEALTH,
  GOAL_OWNER_KINDS,
  GOAL_SUCCESS_STATUSES,
  type Goal,
  type GoalCloseDecision,
  type GoalHealth,
  type GoalOwnerKind,
  type GoalRetrospective,
  type GoalSuccessStatus,
  type GoalTimeframe,
  goalRetrospectives,
  goals,
  INDICATOR_TYPES,
  type IndicatorType,
  KEY_RESULT_DIRECTIONS,
  type KeyResult,
  type KeyResultDirection,
  type KeyResultValue,
  keyResults,
  keyResultValues,
  VALUE_SOURCES,
  type ValueSource,
} from "./schema/goals.ts";
export {
  type InstanceAuditEvent,
  instanceAuditEvents,
} from "./schema/instance-audit.ts";
export {
  type InviteLink,
  type InviteMode,
  inviteLinks,
} from "./schema/invitations.ts";
export {
  KPI_AGGREGATES,
  KPI_DIRECTIONS as KPI_DIRECTION_VALUES,
  KPI_FREQUENCIES as KPI_FREQUENCY_VALUES,
  KPI_OWNER_KINDS,
  KPI_SHARE_ACCESS,
  KPI_STATES as KPI_STATE_VALUES,
  KPI_TIERS,
  type KpiAggregate,
  type KpiCategoryRow,
  type KpiDependencyRow,
  type KpiDirectionValue,
  type KpiFrequencyValue,
  type KpiOwnerKind,
  type KpiRecordRow,
  type KpiRow,
  type KpiShareAccess,
  type KpiShareRow,
  type KpiStateValue,
  type KpiTier,
  type KpiTreeRow,
  kpiCategories,
  kpiDependencies,
  kpiRecords,
  kpiShares,
  kpis,
  kpiTrees,
} from "./schema/kpis.ts";
export {
  NOTIFICATION_REASONS,
  type Notification,
  type NotificationBatch,
  type NotificationBatchStatus,
  type NotificationReason,
  type NotificationRouting,
  type NotificationSettingsRow,
  notificationBatches,
  notificationSettings,
  notifications,
  type Subscription,
  type SubscriptionList,
  type SubscriptionReason,
  subscriptionLists,
  subscriptions,
} from "./schema/notifications.ts";
export { outbox } from "./schema/outbox.ts";
export {
  type PerformanceSnapshotRow,
  PORTFOLIO_VERDICTS,
  type PortfolioVerdictValue,
  performanceSnapshots,
  type ScorecardSettingsRow,
  type ScoreEntryRow,
  SNAPSHOT_OWNER_KINDS,
  type SnapshotOwnerKind,
  scorecardSettings,
  scoreEntries,
} from "./schema/scorecard.ts";
export {
  SPACE_ROLES,
  type Space,
  type SpaceMember,
  type SpaceRole,
  type SpaceSettings,
  spaceMembers,
  spaces,
} from "./schema/spaces.ts";
export { systemSettings } from "./schema/system-settings.ts";
export {
  type QuietHours,
  type Workspace,
  type WorkspaceMember,
  type WorkspaceSettings,
  workspaceMembers,
  workspaces,
} from "./schema/workspaces.ts";
export {
  activeOnly,
  includeDeleted,
  type SoftDeletable,
  softDeleteRows,
} from "./soft-delete.ts";
export {
  collectSoftDeletableTables,
  lintSoftDeleteUsage,
  type SoftDeleteViolation,
  type SourceFile,
} from "./soft-delete-lint.ts";
export {
  INSTANCE_ADMIN_SETTING,
  type TenantContext,
  USER_SETTING,
  WORKSPACE_SETTING,
  type WorkspaceTx,
  withContext,
  withInstanceAdmin,
  withUser,
  withWorkspace,
} from "./tenant.ts";
