import { PACKAGE_NAME as FORMATS } from "@openokr/formats";
import { PACKAGE_NAME as METHOD } from "@openokr/method";

export const PACKAGE_NAME = "@openokr/ui";
export const DEPENDS_ON = [FORMATS, METHOD] as const;

export * from "./components/avatar.tsx";
export * from "./components/bar.tsx";
export * from "./components/button.tsx";
export * from "./components/card.tsx";
export * from "./components/chip.tsx";
export * from "./components/kbd.tsx";
export * from "./components/verdict-dot.tsx";
export * from "./feedback/toast.tsx";
export * from "./fields/code-input.tsx";
export * from "./fields/confidence-format.ts";
export * from "./fields/confidence-input.tsx";
export * from "./fields/email-input.tsx";
export * from "./fields/number-input.tsx";
export * from "./fields/secret-input.tsx";
export * from "./fields/text-input.tsx";
export * from "./fields/timezone-select.tsx";
export * from "./fields/unit-input.tsx";
export * from "./forms/unsaved-changes.tsx";
export * from "./forms/use-form-dirty.ts";
export * from "./forms/use-submit-shortcut.ts";
export * from "./i18n/catalogue.ts";
export { fillTermHole, renamedTerms } from "./i18n/terms.ts";
export * from "./i18n/use-translations.tsx";
export * from "./keyboard/registry.tsx";
export * from "./keyboard/shortcut-overlay.tsx";
export * from "./keyboard/use-keyboard-shortcut.ts";
export * from "./lib/cn.ts";
export * from "./lib/format-measure.ts";
export * from "./query/query-provider.tsx";
export * from "./rich-text/blank.ts";
export * from "./rich-text/draft.ts";
export * from "./rich-text/editor.tsx";
export * from "./rich-text/rich-text-field.tsx";
export * from "./rich-text/use-draft-autosave.ts";
export * from "./rich-text/view.tsx";
export * from "./shell/app-shell.tsx";
export * from "./shell/cycle-strip.tsx";
export * from "./shell/mobile-tab-bar.tsx";
export * from "./shell/sidebar.tsx";
export * from "./shell/topbar.tsx";
export * from "./theme/theme-provider.tsx";
export * from "./theme/theme-script.ts";
export * from "./version/use-stale-deployment.ts";
