import { PACKAGE_NAME as METHOD } from "@openokr/method";

export const PACKAGE_NAME = "@openokr/ui";
export const DEPENDS_ON = [METHOD] as const;

export * from "./components/avatar.tsx";
export * from "./components/bar.tsx";
export * from "./components/button.tsx";
export * from "./components/card.tsx";
export * from "./components/chip.tsx";
export * from "./components/kbd.tsx";
export * from "./components/verdict-dot.tsx";
export * from "./i18n/catalogue.ts";
export * from "./i18n/use-translations.tsx";
export * from "./keyboard/registry.tsx";
export * from "./keyboard/shortcut-overlay.tsx";
export * from "./keyboard/use-keyboard-shortcut.ts";
export * from "./lib/cn.ts";
export * from "./query/query-provider.tsx";
export * from "./rich-text/draft.ts";
export * from "./rich-text/editor.tsx";
export * from "./rich-text/use-draft-autosave.ts";
export * from "./shell/app-shell.tsx";
export * from "./shell/cycle-strip.tsx";
export * from "./shell/mobile-tab-bar.tsx";
export * from "./shell/sidebar.tsx";
export * from "./shell/topbar.tsx";
export * from "./theme/theme-provider.tsx";
export * from "./theme/theme-script.ts";
export * from "./version/use-stale-deployment.ts";
