/**
 * The local disk storage driver: the default, and the only one a
 * self-hosted install needs. S3-compatible storage is an alternative driver
 * behind the same port, never a requirement.
 */
import { createHmac, timingSafeEqual } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import {
  type FileStorage,
  ObjectNotFoundError,
  type PutOptions,
  type StoredObject,
} from "../../ports/storage.ts";

export interface LocalDiskStorageOptions {
  /** Directory blobs live under. Created on demand. */
  readonly root: string;
  /** Secret for signing URLs. Generated by the setup wizard in production. */
  readonly signingSecret: string;
  /** Base path signed URLs are built against. */
  readonly baseUrl?: string;
  readonly defaultExpirySeconds?: number;
}

const DEFAULT_EXPIRY_SECONDS = 300;

export class LocalDiskStorage implements FileStorage {
  readonly #root: string;
  readonly #secret: string;
  readonly #baseUrl: string;
  readonly #defaultExpiry: number;

  constructor(options: LocalDiskStorageOptions) {
    this.#root = resolve(options.root);
    this.#secret = options.signingSecret;
    this.#baseUrl = options.baseUrl ?? "/files";
    this.#defaultExpiry =
      options.defaultExpirySeconds ?? DEFAULT_EXPIRY_SECONDS;
  }

  /**
   * Resolves a key inside the storage root. A key is caller-supplied and may
   * carry a filename that came from a browser, so traversal out of the root
   * is rejected rather than normalised away.
   */
  #resolve(key: string): string {
    const path = resolve(this.#root, key);
    const inside = relative(this.#root, path);
    if (
      inside === "" ||
      inside.startsWith("..") ||
      resolve(this.#root, inside) !== path
    ) {
      throw new Error(`Invalid storage key: ${key}`);
    }
    return path;
  }

  async put(
    key: string,
    body: Buffer,
    options?: PutOptions,
  ): Promise<StoredObject> {
    const path = this.#resolve(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
    const contentType = options?.contentType ?? "application/octet-stream";
    return { key, size: body.byteLength, contentType };
  }

  async get(key: string): Promise<Buffer> {
    const path = this.#resolve(key);
    try {
      return await readFile(path);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") {
        throw new ObjectNotFoundError(key);
      }
      throw error;
    }
  }

  async delete(key: string): Promise<void> {
    // `force` makes deleting an absent object a no-op, which keeps retries
    // and cleanup jobs simple.
    await rm(this.#resolve(key), { force: true });
  }

  async signedUrl(key: string, expiresInSeconds?: number): Promise<string> {
    this.#resolve(key);
    const expires =
      Math.floor(Date.now() / 1000) + (expiresInSeconds ?? this.#defaultExpiry);
    const signature = this.#sign(key, expires);
    const params = new URLSearchParams({ expires: String(expires), signature });
    return `${this.#baseUrl}/${key}?${params.toString()}`;
  }

  /** Checks a signed URL's signature and expiry. Used by the file route. */
  verifySignedUrl(url: string): boolean {
    const [path, query] = url.split("?");
    if (!path || !query) {
      return false;
    }
    const params = new URLSearchParams(query);
    const expires = Number(params.get("expires"));
    const signature = params.get("signature");
    if (!signature || !Number.isFinite(expires)) {
      return false;
    }
    if (expires < Math.floor(Date.now() / 1000)) {
      return false;
    }

    const key = path.slice(`${this.#baseUrl}/`.length);
    const expected = Buffer.from(this.#sign(key, expires));
    const given = Buffer.from(signature);
    // Constant-time compare: a length check first, because timingSafeEqual
    // throws on differing lengths.
    return expected.length === given.length && timingSafeEqual(expected, given);
  }

  #sign(key: string, expires: number): string {
    return createHmac("sha256", this.#secret)
      .update(`${key}:${expires}`)
      .digest("hex");
  }

  async stop(): Promise<void> {
    // Every call above opens and closes its own file handle; nothing is
    // held between calls.
  }
}
