#!/usr/bin/env node
/**
 * The API reference, generated from the contract (P8-T11b).
 *
 * **Written by a script because a hand-written reference is wrong the day
 * after it is written.** The action registry is the one place a read or a
 * write is declared, `contract/openapi.json` is generated from it, and this
 * turns that document into the page a person reads. Three artefacts, one
 * source, and none of them can quietly disagree.
 *
 * Two modes, the same shape `gen:contract` uses: writing, and checking. A
 * generator and a checker that were two programs could differ about what the
 * file should hold, which is the bug this arrangement exists to make
 * impossible.
 *
 *   node scripts/gen-api-reference.ts           writes docs/api/reference.md
 *   node scripts/gen-api-reference.ts --check   fails if the committed file drifted
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(
  /^\/([A-Za-z]:)/,
  "$1",
);
const TARGET = join(ROOT, "docs/api/reference.md");

interface Operation {
  readonly operationId?: string;
  readonly summary?: string;
  readonly tags?: readonly string[];
  readonly "x-openokr-scope"?: string;
  readonly "x-openokr-safety"?: string;
}

interface Contract {
  readonly info?: { readonly version?: string };
  readonly paths: Record<string, Record<string, Operation>>;
}

/** What a safety class means to somebody deciding what to allow. */
const SAFETY: Record<string, string> = {
  read: "reads",
  write: "writes",
  destructive: "destroys",
};

function render(contract: Contract): string {
  const byTag = new Map<
    string,
    { method: string; path: string; op: Operation }[]
  >();

  for (const [path, methods] of Object.entries(contract.paths)) {
    for (const [method, op] of Object.entries(methods)) {
      const tag = op.tags?.[0] ?? "other";
      const list = byTag.get(tag) ?? [];
      list.push({ method: method.toUpperCase(), path, op });
      byTag.set(tag, list);
    }
  }

  const total = [...byTag.values()].reduce((sum, list) => sum + list.length, 0);
  const tags = [...byTag.keys()].sort();

  const lines: string[] = [
    "# API reference",
    "",
    "<!-- Generated by scripts/gen-api-reference.ts from contract/openapi.json.",
    "     Do not edit by hand: `pnpm check:docs` fails when this drifts. -->",
    "",
    `Every read and write OpenOKR offers, ${total} of them, grouped by domain.`,
    "",
    "This page is generated from `contract/openapi.json`, which is generated",
    "from the action registry. The same registry produces the REST surface, the",
    "command line, the agent tool catalogue and the chat commands, so anything",
    "listed here is reachable from all of them on the same terms.",
    "",
    "See [how the API works](README.md) for authentication, scopes, errors and",
    "the machine-readable document.",
    "",
    "## Reading this table",
    "",
    "| Column | Meaning |",
    "|---|---|",
    "| **Action** | The name in the registry. The command line and the agent catalogue use it verbatim |",
    "| **Method and path** | Under `/api/v1` |",
    "| **Class** | `reads` needs the read scope. `writes` and `destroys` need write. A token is never granted destructive by default |",
    "",
    "## Domains",
    "",
    "| Domain | Actions |",
    "|---|---|",
  ];

  for (const tag of tags) {
    const count = (byTag.get(tag) ?? []).length;
    lines.push(`| [${tag}](#${tag}) | ${count} |`);
  }

  for (const tag of tags) {
    const list = (byTag.get(tag) ?? []).sort((a, b) =>
      (a.op.operationId ?? a.path).localeCompare(b.op.operationId ?? b.path),
    );
    lines.push("", `## ${tag}`, "", "| Action | Method and path | Class |", "|---|---|---|");
    for (const { method, path, op } of list) {
      const safety = SAFETY[op["x-openokr-safety"] ?? "read"] ?? "reads";
      const name = op.operationId ?? "";
      const summary = (op.summary ?? "").replace(/\|/g, "\\|");
      lines.push(
        `| \`${name}\`<br/>${summary} | \`${method} /api/v1${path}\` | ${safety} |`,
      );
    }
  }

  lines.push("");
  return lines.join("\n");
}

const contract = JSON.parse(
  await readFile(join(ROOT, "contract/openapi.json"), "utf8"),
) as Contract;

const rendered = render(contract);

if (process.argv.includes("--check")) {
  let committed: string;
  try {
    committed = await readFile(TARGET, "utf8");
  } catch {
    process.stderr.write(
      "docs/api/reference.md is missing. Run `pnpm gen:docs`.\n",
    );
    process.exit(1);
  }
  if (committed !== rendered) {
    process.stderr.write(
      "docs/api/reference.md does not match the contract.\n" +
        "The registry moved and the reference did not. Run `pnpm gen:docs`.\n",
    );
    process.exit(1);
  }
  const actions = Object.values(contract.paths).flatMap((methods) =>
    Object.keys(methods),
  ).length;
  process.stdout.write(
    `API reference check passed. ${actions} action(s), and the committed page agrees.\n`,
  );
} else {
  await writeFile(TARGET, rendered);
  process.stdout.write(`Wrote docs/api/reference.md.\n`);
}
