/**
 * The composition root: builds the driver set for a process and hands back
 * ports only.
 *
 * Every capability has a working default, so a fresh install runs with no
 * configuration: jobs and cache on the database it already has, files on
 * local disk, mail printed to the console, search in Postgres, AI off,
 * channels none. Configuring a provider later swaps a driver behind the same
 * port and changes no feature code.
 *
 * Database access arrives by injection. `packages/adapters` may depend on
 * `packages/config` alone (TECHNICAL-PLAN §1), so it never imports the
 * schema, Drizzle, or the tenant wrapper; the host process passes a pool in.
 */

import { createMailer, type MailerConfig } from "./create-mailer.ts";
import { OffAIProvider } from "./drivers/ai/off.ts";
import { InProcessCache } from "./drivers/cache/in-process.ts";
import {
  type CacheQueryable,
  PostgresCache,
} from "./drivers/cache/postgres.ts";
import { NoneChannel } from "./drivers/channel/none.ts";
import { PgBossJobQueue } from "./drivers/jobs/pg-boss.ts";
import { PostgresRealtime } from "./drivers/realtime/postgres.ts";
import { PostgresSearch } from "./drivers/search/postgres.ts";
import { LocalDiskStorage } from "./drivers/storage/local-disk.ts";
import type { AIProvider } from "./ports/ai.ts";
import type { Cache } from "./ports/cache.ts";
import type { Channel } from "./ports/channel.ts";
import type { JobQueue } from "./ports/jobs.ts";
import type { Mailer } from "./ports/mail.ts";
import type { Realtime } from "./ports/realtime.ts";
import type { Search } from "./ports/search.ts";
import type { FileStorage } from "./ports/storage.ts";

export interface AdapterOptions {
  /** Connection string for pg-boss and the realtime listener. */
  readonly databaseUrl: string;
  /** A pg Pool for the Postgres-backed cache and search drivers. */
  readonly pool: CacheQueryable;
  /** Where local-disk storage keeps its blobs. */
  readonly storageRoot: string;
  /** Secret for signing storage URLs. Generated by the setup wizard. */
  readonly storageSigningSecret: string;
  /** In-process cache instead of the shared Postgres one. Single-process
   * deployments only: a rate limit in process memory is per instance. */
  readonly useInProcessCache?: boolean;
  /** Resolved by the host from the §4.14 instance settings. Console when
   * absent, which is the working default. */
  readonly mail?: MailerConfig;
  readonly onError?: (error: unknown) => void;
}

export interface Adapters {
  readonly jobs: JobQueue;
  readonly realtime: Realtime;
  readonly storage: FileStorage;
  readonly mail: Mailer;
  readonly cache: Cache;
  readonly search: Search;
  readonly ai: AIProvider;
  readonly channel: Channel;
  /** Shuts every driver down. Call on process exit. */
  close(): Promise<void>;
}

export function createAdapters(options: AdapterOptions): Adapters {
  const jobs = new PgBossJobQueue({
    connectionString: options.databaseUrl,
    onError: options.onError,
  });
  const realtime = new PostgresRealtime({
    connectionOptions: { connectionString: options.databaseUrl },
    onError: options.onError,
  });

  return {
    jobs,
    realtime,
    storage: new LocalDiskStorage({
      root: options.storageRoot,
      signingSecret: options.storageSigningSecret,
    }),
    mail: createMailer(options.mail ?? { transport: "console" }),
    cache: options.useInProcessCache
      ? new InProcessCache()
      : new PostgresCache(options.pool),
    search: new PostgresSearch(options.pool),
    ai: new OffAIProvider(),
    channel: new NoneChannel(),
    async close() {
      await Promise.all([jobs.stop(), realtime.stop()]);
    },
  };
}
